sudo: true
language: python
python:
  - "2.7"

before_install:
  - apt-get -y install openmpi=1.6.5

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage

script:
  - python -m pytest IDSort/test

after_script:
  - coveralls
