language: python
python:
  - "3.7"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install openmpi-bin

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage

script:
  - python -m pytest --cov=IDSort --log-format='%(asctime)s.%(msecs)03d %(levelname)8s | %(threadName)s | %(module)s::%(funcName)s::%(lineno)-4d | %(message)s' IDSort/test

after_script:
  - coveralls
