language: python
python:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libopenmpi-dev
  - sudo apt-get -y install openmpi-bin

install:
  - pip install -r requirements.txt
  - pip install coveralls coverage

script:
  - python -m pytest --cov=IDSort --log-format='%(asctime)s.%(msecs)03d %(filename)-25s %(lineno)4d %(levelname)-8s %(message)s' --log-date-format='%Y-%m-%d %H:%M:%S' IDSort/test

after_script:
  - coveralls
